In [14]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier #decision trees
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
# step 1: load data
enviro_data = pd.read_csv('data_participant_ECCC.csv')
enviro_data

/var/folders/dx/66dwwfp55d1032n4tz8r0mz00000gp/T/ipykernel_15942/3807371859.py:2: DtypeWarning: Columns (1270,1271,1272) have mixed types. Specify dtype option on import or set low_memory=False.
  enviro_data = pd.read_csv('data_participant.csv')

,ID,year,month,day,hour,start_time,latitude,longitude,event,r_300.t-6,...,LD.t-2,LD.t-1,LD.t+0,LD.t+1,LD.t+2,LD.t+3,hail_size,y_thunderstorm,y_hail,y_severe
0,0,2005,4,8,4,4/8/2005 4:00,56.12900,-119.081980,NaN,98.769104,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,False,False,False
1,1,2005,4,8,8,4/8/2005 8:00,52.12900,-119.081980,NaN,100.736720,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,False,False,False
2,2,2005,4,13,2,4/13/2005 2:00,48.37900,-114.331790,NaN,33.332287,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,False,False,False
3,3,2005,4,21,2,4/21/2005 2:00,53.87900,-105.831436,NaN,83.939270,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,False,False,False
4,4,2005,5,3,21,5/3/2005 21:00,52.87900,-115.831850,NaN,95.186860,...,0.000048,0.000451,0.001993,0.004847,0.000247,0.001017,0.0,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9542,2022,6,30,1,6/30/2022 1:25,51.79841,-100.486810,2733.0,87.580380,...,2.484526,2.484526,2.484526,2.484526,2.484526,2.484526,21.0,NaN,NaN,NaN
9996,9543,2022,6,30,2,6/30/2022 2:20,51.89355,-99.637400,2733.0,86.444176,...,2.009431,2.009431,2.009431,2.009431,2.009431,2.009431,21.0,NaN,NaN,NaN
9997,9544,2022,6,30,2,6/30/2022 2:17,51.64718,-99.924870,2733.0,74.155975,...,1.972132,1.972132,1.972132,1.972132,1.972132,1.972132,21.0,NaN,NaN,NaN
9998,9545,2022,6,30,18,6/30/2022 18:55,55.74510,-97.850920,2734.0,15.329826,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.0,NaN,NaN,NaN
9999,9546,2022,6,24,4,6/24/2022 4:14,50.68439,-102.474190,2735.0,33.908690,...,2.120244,2.120244,2.120244,2.120244,2.120244,2.120244,26.5,NaN,NaN,NaN

In [4]:
# step 2: clean data
df_thun = enviro_data.drop(columns = ['year', 'month', 'day', 'hour', 'start_time', 'latitude', 'longitude', 'event', 'y_hail', 'y_severe'])
df_hail = enviro_data.drop(columns = ['year', 'month', 'day', 'hour', 'start_time', 'latitude', 'longitude', 'event', 'y_thunderstorm', 'y_severe'])
df_sev = enviro_data.drop(columns = ['year', 'month', 'day', 'hour', 'start_time', 'latitude', 'longitude', 'event', 'y_thunderstorm', 'y_hail'])

In [5]:
# step 3: split the data into training/test sets

# find prediction data
prediction_df_thun = df_thun[df_thun['y_thunderstorm'].isna()]
prediction_df_hail = df_hail[df_hail['y_hail'].isna()]
prediction_df_sev = df_sev[df_sev['y_severe'].isna()]

# find remaining dataset
dataset_thun = df_thun.dropna(how='any')
dataset_hail = df_hail.dropna(how='any')
dataset_sev = df_sev.dropna(how='any')

# split into training and testing
X_thun = dataset_thun.drop(columns = ['y_thunderstorm'])
y_thun = dataset_thun['y_thunderstorm']

X_hail = dataset_hail.drop(columns = ['y_hail'])
y_hail = dataset_hail['y_hail']

X_sev = dataset_sev.drop(columns = ['y_severe'])
y_sev = dataset_sev['y_severe']


# convert true false to 0, 1
label_encoder = LabelEncoder()
y_thun = label_encoder.fit_transform(y_thun)
y_hail = label_encoder.fit_transform(y_hail)
y_sev = label_encoder.fit_transform(y_sev)

# split into 80% traiing, 20% testing
X_train_thun, X_test_thun, y_train_thun, y_test_thun = train_test_split(X_thun, y_thun, test_size = 0.2)
X_train_hail, X_test_hail, y_train_hail, y_test_hail = train_test_split(X_hail, y_hail, test_size = 0.2)
X_train_sev, X_test_sev, y_train_sev, y_test_sev = train_test_split(X_sev, y_sev, test_size = 0.2)

In [6]:
# step 4 & 5: create model (decision tree) & train model
model_thun = DecisionTreeClassifier()
model_thun.fit(X_train_thun.drop(columns=['ID']), y_train_thun)

model_hail = DecisionTreeClassifier()
model_hail.fit(X_train_hail.drop(columns=['ID']), y_train_hail)

model_sev = DecisionTreeClassifier()
model_sev.fit(X_train_sev.drop(columns=['ID']), y_train_sev)

DecisionTreeClassifier()

In [7]:
# step 6: make predictions and check accuracy to tune model
predictions_thun = model_thun.predict(X_test_thun.drop(columns=['ID']))
accuracy_score(y_test_thun, predictions_thun)

predictions_hail = model_hail.predict(X_test_hail.drop(columns=['ID']))
accuracy_score(y_test_hail, predictions_hail)

predictions_sev = model_sev.predict(X_test_sev.drop(columns=['ID']))
accuracy_score(y_test_sev, predictions_sev)

array([1, 1, 1, ..., 1, 0, 1])

In [12]:
# step 7: use the model
act_predictions_thun = model_thun.predict(prediction_df_thun.drop(columns = ['y_thunderstorm', 'ID']))
act_predictions_hail = model_hail.predict(prediction_df_hail.drop(columns = ['y_hail', 'ID']))
act_predictions_sev = model_sev.predict(prediction_df_sev.drop(columns = ['y_severe', 'ID']))

# convert actual predictions back to True, False
pred_tf_thun = act_predictions_thun.astype(bool)
pred_tf_hail = act_predictions_hail.astype(bool)
pred_tf_sev = act_predictions_sev.astype(bool)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [9]:
# filter for ID, predictions
prediction_df_thun.loc[:,'y_thunderstorm'] = pred_tf_thun
to_add_thun = prediction_df_thun[['ID', 'y_thunderstorm']]

prediction_df_hail.loc[:,'y_hail'] = pred_tf_hail
to_add_hail= prediction_df_hail[['ID', 'y_hail']]

prediction_df_sev.loc[:,'y_severe'] = pred_tf_sev
to_add_sev= prediction_df_sev[['ID', 'y_severe']]

In [10]:
# replace original data with predicition, matching using ID
enviro_data.set_index('ID', inplace=True)
to_add_thun.set_index('ID', inplace=True)
to_add_hail.set_index('ID', inplace=True)
to_add_sev.set_index('ID', inplace=True)

enviro_data.update(to_add_thun)
enviro_data.update(to_add_hail)
enviro_data.update(to_add_sev)

enviro_data.reset_index(inplace=True)

In [16]:
# save to output csv file
enviro_data.to_csv('output_environCan', index=False)